version: "3.8"
services:
    app:
        build:
            args:
                user: luong
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: skp
        container_name: laravel-basic
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
            - ./:/var/www
        networks:
            - luong

    db_luong:
        image: mysql:latest
        container_name: mysql_db
        restart: unless-stopped
        ports:
            - 3308:3306
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            MYSQL_PASSWORD: ${DB_PASSWORD}
            MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker/sql:/docker-entrypoint-initdb.d
        networks:
            - luong
    phpmyadmin:
        image: phpmyadmin:5.2.0
        container_name: php_myadmin
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: ${DB_HOST}
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            PMA_PORT: ${DB_PORT}
        depends_on:
            - db_luong
        ports:
            - 8888:80
        networks:
            - luong

    nginx:
        image: nginx:alpine
        container_name: nginx_server
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker/nginx:/etc/nginx/conf.d/
        networks:
            - luong
networks:
    luong:
        driver: bridge
